import { Router } from 'express';
import { createChapter, getChapters, readChapter, getChapterEditor, updateChapter, deleteChapter } from '../controllers/chapter.controller.js';
import { isAuth } from '../middlewares/isAuth.js';
import { validateCsrfToken } from '../middlewares/csrf.js';
const router = Router();
router.post('/new', isAuth, validateCsrfToken, createChapter);
router.put('/update/:id', isAuth, validateCsrfToken, updateChapter);
router.delete('/delete/:id', isAuth, validateCsrfToken, deleteChapter);
router.get('/story/:id', getChapters);
router.get('/read/:id', readChapter);
router.get('/nuevo/:storyId', isAuth, getChapterEditor);
router.get('/editar/:id', isAuth, getChapterEditor);
export default router;
