import { Router } from 'express';
import { isAuth } from '../middlewares/isAuth.js';
import { validateCsrfToken } from '../middlewares/csrf.js';
import { seguirUsuario, dejarDeSeguir, estadoSeguimiento, darLike, quitarLike, agregarALista, quitarDeLista, getComentarios, postComentario, deleteComentario } from '../controllers/social.controller.js';
const router = Router();
router.post('/seguir/:id', isAuth, validateCsrfToken, seguirUsuario);
router.post('/dejar/:id', isAuth, validateCsrfToken, dejarDeSeguir);
router.get('/estado/:id', isAuth, estadoSeguimiento);
router.post('/like/:id', isAuth, validateCsrfToken, darLike);
router.post('/unlike/:id', isAuth, validateCsrfToken, quitarLike);
router.post('/lista/agregar/:id', isAuth, validateCsrfToken, agregarALista);
router.post('/lista/quitar/:id', isAuth, validateCsrfToken, quitarDeLista);
router.get('/comentarios/:cuentoId', getComentarios);
router.post('/comentarios/:cuentoId', isAuth, validateCsrfToken, postComentario);
router.delete('/comentarios/borrar/:comentarioId', isAuth, validateCsrfToken, deleteComentario);
export default router;
